### PR TITLE
Allow Django apps to use buckets for files

### LINKED ISSUE #331: Add configuration settings to use buckets for file upload.
To use the GCS bucket we must set the correct settings in settings.py. For more information https://django-storages.readthedocs.io/en/latest/backends/gcloud.html#getting-started

### PR DESCRIPTION
**Pull request by enriquejosepadilla**
fixes #331

### CODE REVIEW

**Comment by wangxf123456** [comment]
Can we merge this branch with master? It contains changes from the previous PR.

**Comment by enriquejosepadilla** [comment]
Hmmm , let me see if i pull from master it removes the changes from previous PR.
But mergining i believe shouldn't cause an issue if its the same code.

**Comment by enriquejosepadilla** [comment]
Sadly it doesn't "remove" the commit history of the other PR, i will avoid doing this in the future. There doesn't seem any issue with merging.

**Comment by wangxf123456** [comment]
I think it is fine to leave the commit history here.

**Pull request merged**
